/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPreflight, IPreflightInterface } from "../IPreflight";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_origin",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_nonce",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "_sender",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
    ],
    name: "preflight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPreflight__factory {
  static readonly abi = _abi;
  static createInterface(): IPreflightInterface {
    return new utils.Interface(_abi) as IPreflightInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPreflight {
    return new Contract(address, _abi, signerOrProvider) as IPreflight;
  }
}
